name: Build & publish PHP images with extensions

on:
  workflow_dispatch:
  schedule:
   - cron: "0 0 * * *"

permissions:
  contents: write
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE: marlub/php

jobs:
  update-matrix:
    name: Update matrix
    runs-on: ubuntu-latest
    
    outputs:
      registry: ${{ steps.prepare_build_vars.outputs.registry }}
      image: ${{ steps.prepare_build_vars.outputs.image }}
      matrix: ${{ steps.prepare_build_vars.outputs.matrix }}

    steps:
      - name: Authenticate as GH Action Admin
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GH_ACTIONS_ADMIN_APP_ID }}
          private-key: ${{ secrets.GH_ACTIONS_ADMIN_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: python -m pip install requests packaging

      - name: Update matrix.json
        run: |
          python scripts/update_matrix.py

      - name: Commit matrix.json if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@example.com"

          if ! git diff --quiet matrix.json; then
            git add matrix.json
            git commit -m "Update matrix.json [auto]"
            git push
          fi

      - name: Prepare build variables
        id: prepare_build_vars
        run: |
          echo "registry=$REGISTRY" >> $GITHUB_OUTPUT
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "matrix=$(jq -c . < matrix.json)" >> $GITHUB_OUTPUT

  build-and-test:
    name: Build and test
    needs: update-matrix
    uses: ./.github/workflows/template-images.yml
    with:
      publish: true
      registry: ${{ needs.update-matrix.outputs.registry }}
      image: ${{ needs.update-matrix.outputs.image }}
      matrix: ${{ needs.update-matrix.outputs.matrix }}

  publish-manifest:
    name: Publish image tags
    runs-on: ubuntu-latest
    needs:
      - update-matrix
      - build-and-test
    if: "always() && (needs.update-matrix.result == 'success')"
    steps:
      - name: Download digests
        uses: actions/download-artifact@v7
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create manifest from digests
        env:
          MATRIX: ${{ needs.update-matrix.outputs.matrix }}
        run: |
          IMAGES_TAGGED=0
          for dir in ${{ runner.temp }}/digests/*; do
            ARTIFACTS_COUNT=$(ls -1 "$dir" | wc -l)
            if [ "$ARTIFACTS_COUNT" = "2" ]; then
              ((++IMAGES_TAGGED))
              DIGESTS=$(jq -r '.digest' "$dir"/*.json)
              TAG_MINOR=$(jq -r '.tagMinor' "$dir"/*.json | head -n1)
              TAG_PATCH=$(jq -r '.tagPatch' "$dir"/*.json | head -n1)

              docker buildx imagetools create --tag "${{ env.REGISTRY }}/${{ env.IMAGE }}:$TAG_PATCH" $DIGESTS
              docker buildx imagetools create --tag "${{ env.REGISTRY }}/${{ env.IMAGE }}:$TAG_MINOR" $DIGESTS
            else
              echo "The artifacts count $ARTIFACTS_COUNT is invalid for: $dir"
            fi
          done

          IMAGE_VARIANTS=$(echo "$MATRIX" | jq '.[] | length')
          echo "$IMAGES_TAGGED / $IMAGE_VARIANTS images are tagged"
          if [ "$IMAGES_TAGGED" != "$IMAGE_VARIANTS" ]; then
            exit 1
          fi
