name: Build & publish PHP images with extensions

on:
  workflow_dispatch:
  schedule:
   - cron: "0 0 * * *"

permissions:
  contents: write
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE: marlub/php

jobs:
  update-matrix:
    name: Update matrix
    runs-on: ubuntu-latest
    
    outputs:
      registry: ${{ steps.prepare_build_vars.outputs.registry }}
      image: ${{ steps.prepare_build_vars.outputs.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: python -m pip install requests packaging

      - name: Update matrix.json
        run: |
          python scripts/update_matrix.py

      - name: Commit matrix.json if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@example.com"

          if ! git diff --quiet matrix.json; then
            git add matrix.json
            git commit -m "Update matrix.json [auto]"
            git push
          fi

      - name: Prepare build variables
        id: prepare_build_vars
        run: |
          echo "registry=$REGISTRY" >> $GITHUB_OUTPUT
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

  build-and-test:
    name: Build and test
    needs: update-matrix
    uses: ./.github/workflows/build-test.yml
    with:
      publish: true
      registry: ${{ needs.update-matrix.outputs.registry }}
      image: ${{ needs.update-matrix.outputs.image }}

  publish-manifest:
    name: Publish image tags
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create manifest from digests
        run: |
          for dir in ${{ runner.temp }}/digests/*; do
            DIGESTS=$(jq -r '.digest' "$dir"/*.json)
            TAG_MINOR=$(jq -r '.tagMinor' "$dir"/*.json | head -n1)
            TAG_PATCH=$(jq -r '.tagPatch' "$dir"/*.json | head -n1)

            docker buildx imagetools create --tag "${{ env.REGISTRY }}/${{ env.IMAGE }}:$TAG_PATCH" $DIGESTS
            docker buildx imagetools create --tag "${{ env.REGISTRY }}/${{ env.IMAGE }}:$TAG_MINOR" $DIGESTS
          done
